[build]
  publish = "src"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self';"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/calculator/*"
  to = "/calculators/:splat"
  status = 301

[[redirects]]
  from = "/calc/*"
  to = "/calculators/:splat"
  status = 301