[build]
  publish = "src"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Edge functions
[[edge_functions]]
  path = "/*"
  function = "csp-nonce"

# Headers are defined in _headers file for more control

# Redirects are defined in _redirects file for more control

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Function configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Development settings
[dev]
  port = 8888
  targetPort = 3000
  publish = "src"
  autoLaunch = false

# Context-specific settings
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    performance = 0.9
    accessibility = 0.95
    best-practices = 0.95
    seo = 0.95